version: '3'
services:
  flowci-agent:
    image: flowci/agent:latest
    network_mode: "host"
    ports:
    - "8088:8088"
    environment:
      FLOWCI_SERVER_URL: ${AGENT_SERVER_URL}
      FLOWCI_AGENT_TOKEN: ${AGENT_TOKEN}
      FLOWCI_AGENT_PORT: 8088
      FLOWCI_AGENT_LOG_LEVEL: INFO
    volumes:
      - ${HOME}/.flow.ci.agent:/root/.flow.ci.agent